# Generated by Django 4.2.19 on 2025-11-15 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('explanations', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='current_posts/')),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 20, 15, 7, 102033, tzinfo=datetime.timezone.utc)),
        ),
    ]
