# Generated by Django 4.2.19 on 2025-11-15 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_currentposts_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentposts',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 20, 23, 7, 67040, tzinfo=datetime.timezone.utc)),
        ),
    ]
