# Generated by Django 4.2.19 on 2025-11-15 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_currentposts_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentposts',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 20, 28, 57, 101631, tzinfo=datetime.timezone.utc)),
        ),
    ]
