# Generated by Django 4.2.19 on 2025-11-17 16:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_currentposts_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 16, 49, 31, 194871, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Araclar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arac_markasi', models.CharField(max_length=256)),
                ('arac_modeli', models.CharField(max_length=256)),
                ('arac_no', models.CharField(max_length=600)),
                ('arac_plakasi', models.CharField(max_length=256)),
                ('is_removed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arac_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
