# Generated by Django 4.2.19 on 2025-11-17 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_alter_passwordresetcode_expires_at_araclar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='araclar',
            name='arac_no',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 17, 3, 53, 541677, tzinfo=datetime.timezone.utc)),
        ),
    ]
