# Generated by Django 4.2.19 on 2025-11-19 00:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_alter_araclar_arac_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hatirlaticilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatirlatma_turu', models.CharField(choices=[('muayene', 'Muayene'), ('vergi', 'Vergi'), ('sigorta', 'Sigorta')], max_length=20)),
                ('son_tarih', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatirlatma_arac', to='appname.araclar')),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 19, 0, 25, 48, 326412, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='HatirlatmaTarihleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('saat', models.TimeField(default=datetime.time(9, 0))),
                ('hatirlatici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatirlatma_tarihleri', to='appname.hatirlaticilar')),
            ],
        ),
    ]
