# Generated by Django 4.2.19 on 2025-11-19 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_hatirlaticilar_alter_passwordresetcode_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatirlaticilar',
            name='is_active',
        ),
        migrations.AddField(
            model_name='hatirlaticilar',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 19, 16, 8, 58, 254188, tzinfo=datetime.timezone.utc)),
        ),
    ]
