# Generated by Django 4.2.19 on 2025-11-22 04:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_remove_hatirlaticilar_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatirlatmatarihleri',
            name='saat',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 4, 18, 8, 625075, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('hatirlatma_tarihleri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifcation', to='appname.hatirlatmatarihleri')),
            ],
        ),
    ]
