# Generated by Django 4.2.19 on 2025-11-24 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_alter_hatirlatmatarihleri_saat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatirlaticilar',
            name='is_stopped',
        ),
        migrations.AddField(
            model_name='hatirlatmatarihleri',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 24, 16, 54, 36, 371240, tzinfo=datetime.timezone.utc)),
        ),
    ]
