# Generated by Django 4.2.19 on 2025-12-02 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0010_remove_hatirlaticilar_is_stopped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='player_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 9, 0, 48, 668436, tzinfo=datetime.timezone.utc)),
        ),
    ]
