# Generated by Django 4.2.19 on 2025-12-06 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0011_customuser_player_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 6, 21, 3, 46, 896192, tzinfo=datetime.timezone.utc)),
        ),
    ]
